name: educational-forum-test

services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-forum_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-forum_pass}
      POSTGRES_DB: ${POSTGRES_DB:-forum_db}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-forum_user} -d ${POSTGRES_DB:-forum_db}"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"
    networks:
      - app-network
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:8000/', timeout=2)"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 15s
    environment:
      DATABASE_URL: postgresql+asyncpg://${POSTGRES_USER:-forum_user}:${POSTGRES_PASSWORD:-forum_pass}@db:5432/${POSTGRES_DB:-forum_db}
      SECRET_KEY: ${SECRET_KEY}
      ACCESS_TOKEN_EXPIRE_MINUTES: ${ACCESS_TOKEN_EXPIRE_MINUTES:-30}
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - ./backend/migration:/app/alembic
      - ./backend/alembic.ini:/app/alembic.ini
    networks:
      - app-network

  adminer:
    image: adminer:latest
    container_name: forum_adminer
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      ADMINER_DEFAULT_SERVER: db
    depends_on:
      - db
    networks:
      - app-network


  # frontend:
  #   build: 
  #     context: ./frontend
  #     dockerfile: Dockerfile
  #   healthcheck:
  #     test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://127.0.0.1:3000"]
  #     interval: 10s
  #     timeout: 5s
  #     retries: 3
  #     start_period: 10s
  #   depends_on:
  #     backend:
  #       condition: service_healthy
  #   ports:
  #     - "3000:3000"
  #   volumes:
  #     - ./frontend:/app
  #   networks:
  #     - app-network

networks:
  app-network:
    driver: bridge