"""init

Revision ID: 576a12376ccc
Revises: 
Create Date: 2026-04-14 19:30:55.520312

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '576a12376ccc'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
    sa.Column('id_role', sa.Integer(), nullable=False),
    sa.Column('role_name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id_role'),
    sa.UniqueConstraint('role_name')
    )
    op.create_index(op.f('ix_roles_id_role'), 'roles', ['id_role'], unique=False)
    op.create_table('subjects',
    sa.Column('id_subject', sa.Integer(), nullable=False),
    sa.Column('subject_name', sa.String(length=100), nullable=False),
    sa.Column('count_of_tasks', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id_subject'),
    sa.UniqueConstraint('subject_name')
    )
    op.create_index(op.f('ix_subjects_id_subject'), 'subjects', ['id_subject'], unique=False)
    op.create_table('users',
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('surname', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('wallet', sa.String(length=100), nullable=True),
    sa.Column('subscribed_until_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id_role', sa.Integer(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['id_role'], ['roles.id_role'], ),
    sa.PrimaryKeyConstraint('id_user')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id_user'), 'users', ['id_user'], unique=False)
    op.create_table('tasks',
    sa.Column('id_task', sa.Integer(), nullable=False),
    sa.Column('condition', sa.Text(), nullable=False),
    sa.Column('image', sa.String(length=255), nullable=True),
    sa.Column('solution', sa.Text(), nullable=True),
    sa.Column('answer', sa.String(length=255), nullable=False),
    sa.Column('task_number', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('draft', 'public', 'rejected', 'archived', name='taskstatus'), nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.Column('id_subject', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_subject'], ['subjects.id_subject'], ),
    sa.ForeignKeyConstraint(['id_user'], ['users.id_user'], ),
    sa.PrimaryKeyConstraint('id_task')
    )
    op.create_index(op.f('ix_tasks_id_task'), 'tasks', ['id_task'], unique=False)
    op.create_table('solution_views',
    sa.Column('id_solution_view', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('id_task', sa.Integer(), nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_task'], ['tasks.id_task'], ),
    sa.ForeignKeyConstraint(['id_user'], ['users.id_user'], ),
    sa.PrimaryKeyConstraint('id_solution_view')
    )
    op.create_index(op.f('ix_solution_views_id_solution_view'), 'solution_views', ['id_solution_view'], unique=False)
    op.create_table('task_comment',
    sa.Column('id_task_comment', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('id_task', sa.Integer(), nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['id_task'], ['tasks.id_task'], ),
    sa.ForeignKeyConstraint(['id_user'], ['users.id_user'], ),
    sa.PrimaryKeyConstraint('id_task_comment')
    )
    op.create_index(op.f('ix_task_comment_id_task_comment'), 'task_comment', ['id_task_comment'], unique=False)
    op.create_table('task_rating',
    sa.Column('id_task_rating', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('id_task', sa.Integer(), nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_task'], ['tasks.id_task'], ),
    sa.ForeignKeyConstraint(['id_user'], ['users.id_user'], ),
    sa.PrimaryKeyConstraint('id_task_rating')
    )
    op.create_index(op.f('ix_task_rating_id_task_rating'), 'task_rating', ['id_task_rating'], unique=False)
    op.create_table('view_history',
    sa.Column('id_view_history', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('id_task', sa.Integer(), nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_task'], ['tasks.id_task'], ),
    sa.ForeignKeyConstraint(['id_user'], ['users.id_user'], ),
    sa.PrimaryKeyConstraint('id_view_history')
    )
    op.create_index(op.f('ix_view_history_id_view_history'), 'view_history', ['id_view_history'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_view_history_id_view_history'), table_name='view_history')
    op.drop_table('view_history')
    op.drop_index(op.f('ix_task_rating_id_task_rating'), table_name='task_rating')
    op.drop_table('task_rating')
    op.drop_index(op.f('ix_task_comment_id_task_comment'), table_name='task_comment')
    op.drop_table('task_comment')
    op.drop_index(op.f('ix_solution_views_id_solution_view'), table_name='solution_views')
    op.drop_table('solution_views')
    op.drop_index(op.f('ix_tasks_id_task'), table_name='tasks')
    op.drop_table('tasks')
    op.drop_index(op.f('ix_users_id_user'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_subjects_id_subject'), table_name='subjects')
    op.drop_table('subjects')
    op.drop_index(op.f('ix_roles_id_role'), table_name='roles')
    op.drop_table('roles')
    # ### end Alembic commands ###
